-- MetroPulse360
-- 06 - Data Quality & Deduplication

USE DATABASE METRO_DB;
USE SCHEMA STAGING;
USE WAREHOUSE METRO_WH;


-- Create a clean view by keeping the latest
-- record for each TRIP_ID

CREATE OR REPLACE VIEW VW_CLEAN_METRO_TRIPS AS
SELECT
    TRIP_ID,
    PASSENGER_ID,
    ENTRY_STATION_ID,
    EXIT_STATION_ID,
    TRAVEL_DATE,
    FARE,
    LOADED_AT,
    PROCESSED_AT
FROM METRO_DB.STAGING.METRO_TRIPS_STAGING
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY TRIP_ID
    ORDER BY LOADED_AT DESC
) = 1;


-- Load only new, non-duplicate trips
-- into the warehouse fact table

INSERT INTO METRO_DB.DW.FACT_TRIPS (
    TRIP_ID,
    PASSENGER_ID,
    ENTRY_STATION_ID,
    EXIT_STATION_ID,
    TRAVEL_DATE,
    FARE
)
SELECT
    C.TRIP_ID,
    C.PASSENGER_ID,
    C.ENTRY_STATION_ID,
    C.EXIT_STATION_ID,
    C.TRAVEL_DATE,
    C.FARE
FROM METRO_DB.STAGING.VW_CLEAN_METRO_TRIPS C
WHERE NOT EXISTS (
    SELECT 1
    FROM METRO_DB.DW.FACT_TRIPS F
    WHERE F.TRIP_ID = C.TRIP_ID
);


-- Duplicate check

SELECT
    TRIP_ID,
    COUNT(*) AS DUPLICATE_COUNT
FROM METRO_DB.STAGING.METRO_TRIPS_STAGING
GROUP BY TRIP_ID
HAVING COUNT(*) > 1;


-- Verify clean records

SELECT COUNT(*) AS CLEAN_TRIPS
FROM METRO_DB.STAGING.VW_CLEAN_METRO_TRIPS;
