-- MetroPulse360
-- 07 - Analytics Views

USE DATABASE METRO_DB;
USE SCHEMA ANALYTICS;
USE WAREHOUSE METRO_WH;


-- Daily Metro Performance

CREATE OR REPLACE VIEW VW_DAILY_METRO_PERFORMANCE AS
SELECT
    TRAVEL_DATE,
    COUNT(*) AS TOTAL_TRIPS,
    COUNT(DISTINCT PASSENGER_ID) AS UNIQUE_PASSENGERS,
    SUM(FARE) AS TOTAL_REVENUE,
    ROUND(AVG(FARE), 2) AS AVERAGE_FARE
FROM METRO_DB.DW.FACT_TRIPS
GROUP BY TRAVEL_DATE;


-- Station Performance

CREATE OR REPLACE VIEW VW_STATION_PERFORMANCE AS
SELECT
    S.STATION_ID,
    S.STATION_NAME,
    S.LINE_NAME,
    COUNT(F.TRIP_ID) AS TOTAL_ENTRY_TRIPS,
    SUM(F.FARE) AS TOTAL_REVENUE,
    ROUND(AVG(F.FARE), 2) AS AVERAGE_FARE
FROM METRO_DB.DW.DIM_STATION S
LEFT JOIN METRO_DB.DW.FACT_TRIPS F
    ON S.STATION_ID = F.ENTRY_STATION_ID
GROUP BY
    S.STATION_ID,
    S.STATION_NAME,
    S.LINE_NAME;


-- Line Performance

CREATE OR REPLACE VIEW VW_LINE_PERFORMANCE AS
SELECT
    S.LINE_ID,
    S.LINE_NAME,
    COUNT(F.TRIP_ID) AS TOTAL_TRIPS,
    SUM(F.FARE) AS TOTAL_REVENUE,
    ROUND(AVG(F.FARE), 2) AS AVERAGE_FARE
FROM METRO_DB.DW.DIM_STATION S
LEFT JOIN METRO_DB.DW.FACT_TRIPS F
    ON S.STATION_ID = F.ENTRY_STATION_ID
GROUP BY
    S.LINE_ID,
    S.LINE_NAME;


-- Metro KPI Summary

CREATE OR REPLACE VIEW VW_METRO_KPIS AS
SELECT
    COUNT(*) AS TOTAL_TRIPS,
    COUNT(DISTINCT PASSENGER_ID) AS UNIQUE_PASSENGERS,
    SUM(FARE) AS TOTAL_REVENUE,
    ROUND(AVG(FARE), 2) AS AVERAGE_FARE,
    MIN(TRAVEL_DATE) AS FIRST_TRAVEL_DATE,
    MAX(TRAVEL_DATE) AS LAST_TRAVEL_DATE
FROM METRO_DB.DW.FACT_TRIPS;


-- Daily Demand

CREATE OR REPLACE VIEW VW_DAILY_DEMAND AS
SELECT
    TRAVEL_DATE,
    COUNT(*) AS TOTAL_TRIPS,
    SUM(FARE) AS TOTAL_REVENUE,
    ROUND(AVG(FARE), 2) AS AVERAGE_FARE
FROM METRO_DB.DW.FACT_TRIPS
GROUP BY TRAVEL_DATE;


-- Verify views

SHOW VIEWS IN SCHEMA METRO_DB.ANALYTICS;
