-- MetroPulse360
-- 10 - Metro Disruption Analytics

USE DATABASE METRO_DB;
USE SCHEMA ANALYTICS;
USE WAREHOUSE METRO_WH;


-- Disruption events

CREATE OR REPLACE TABLE METRO_DISRUPTIONS (
    DISRUPTION_ID VARCHAR(30),
    LINE_ID VARCHAR(10),
    STATION_ID VARCHAR(10),
    DISRUPTION_TYPE VARCHAR(50),
    SEVERITY VARCHAR(20),
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    IMPACTED_TRIPS NUMBER,
    DESCRIPTION VARCHAR(200)
);


-- Disruption Summary

CREATE OR REPLACE VIEW VW_DISRUPTION_SUMMARY AS
SELECT
    COUNT(*) AS TOTAL_DISRUPTIONS,
    SUM(IMPACTED_TRIPS) AS TOTAL_IMPACTED_TRIPS,
    COUNT_IF(SEVERITY = 'HIGH') AS HIGH_SEVERITY_EVENTS,
    COUNT_IF(SEVERITY = 'MEDIUM') AS MEDIUM_SEVERITY_EVENTS,
    COUNT_IF(SEVERITY = 'LOW') AS LOW_SEVERITY_EVENTS
FROM METRO_DISRUPTIONS;


-- Disruption Severity Analysis

CREATE OR REPLACE VIEW VW_DISRUPTION_SEVERITY AS
SELECT
    SEVERITY,
    COUNT(*) AS DISRUPTION_COUNT,
    SUM(IMPACTED_TRIPS) AS IMPACTED_TRIPS
FROM METRO_DISRUPTIONS
GROUP BY SEVERITY
ORDER BY
    CASE SEVERITY
        WHEN 'HIGH' THEN 1
        WHEN 'MEDIUM' THEN 2
        WHEN 'LOW' THEN 3
        ELSE 4
    END;


-- Line-level Disruption Analysis

CREATE OR REPLACE VIEW VW_LINE_DISRUPTION_ANALYTICS AS
SELECT
    LINE_ID,
    COUNT(*) AS TOTAL_DISRUPTIONS,
    SUM(IMPACTED_TRIPS) AS IMPACTED_TRIPS,
    COUNT_IF(SEVERITY = 'HIGH') AS HIGH_SEVERITY_EVENTS
FROM METRO_DISRUPTIONS
GROUP BY LINE_ID
ORDER BY IMPACTED_TRIPS DESC;


-- Verify disruption analytics

SELECT *
FROM VW_DISRUPTION_SUMMARY;

SELECT *
FROM VW_DISRUPTION_SEVERITY;

SELECT *
FROM VW_LINE_DISRUPTION_ANALYTICS;
