-- MetroPulse360
-- 02 - Data Warehouse Data Model
-- Star Schema: Fact + Dimension Tables

USE DATABASE METRO_DB;
USE SCHEMA DW;
USE WAREHOUSE METRO_WH;

-- Passenger Dimension

CREATE OR REPLACE TABLE DIM_PASSENGER (
    PASSENGER_ID VARCHAR(20),
    GENDER VARCHAR(10)
);

INSERT INTO DIM_PASSENGER (
    PASSENGER_ID,
    GENDER
)
VALUES
    ('P1001', 'Male'),
    ('P1002', 'Female'),
    ('P1003', 'Male'),
    ('P1004', 'Female'),
    ('P1005', 'Male');


-- Date Dimension

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID DATE,
    DAY_NUMBER NUMBER,
    DAY_NAME VARCHAR(20),
    MONTH_NUMBER NUMBER,
    MONTH_NAME VARCHAR(20),
    QUARTER_NUMBER NUMBER,
    YEAR_NUMBER NUMBER,
    IS_WEEKEND BOOLEAN
);

INSERT INTO DIM_DATE (
    DATE_ID,
    DAY_NUMBER,
    DAY_NAME,
    MONTH_NUMBER,
    MONTH_NAME,
    QUARTER_NUMBER,
    YEAR_NUMBER,
    IS_WEEKEND
)
SELECT
    DATEADD(DAY, SEQ4(), '2026-01-01') AS DATE_ID,
    DAY(DATEADD(DAY, SEQ4(), '2026-01-01')) AS DAY_NUMBER,
    DAYNAME(DATEADD(DAY, SEQ4(), '2026-01-01')) AS DAY_NAME,
    MONTH(DATEADD(DAY, SEQ4(), '2026-01-01')) AS MONTH_NUMBER,
    MONTHNAME(DATEADD(DAY, SEQ4(), '2026-01-01')) AS MONTH_NAME,
    QUARTER(DATEADD(DAY, SEQ4(), '2026-01-01')) AS QUARTER_NUMBER,
    YEAR(DATEADD(DAY, SEQ4(), '2026-01-01')) AS YEAR_NUMBER,
    DAYOFWEEK(DATEADD(DAY, SEQ4(), '2026-01-01')) IN (0, 6) AS IS_WEEKEND
FROM TABLE(GENERATOR(ROWCOUNT => 365));


-- Line Dimension

CREATE OR REPLACE TABLE DIM_LINE (
    LINE_ID VARCHAR(10),
    LINE_NAME VARCHAR(50),
    LINE_STATUS VARCHAR(30)
);

INSERT INTO DIM_LINE (
    LINE_ID,
    LINE_NAME,
    LINE_STATUS
)
SELECT
    LINE_ID,
    LINE_NAME,
    LINE_STATUS
FROM METRO_DB.RAW.LINES;


-- Station Dimension

CREATE OR REPLACE TABLE DIM_STATION (
    STATION_ID VARCHAR(10),
    STATION_NAME VARCHAR(100),
    LINE_ID VARCHAR(10),
    LINE_NAME VARCHAR(50),
    STATION_SEQUENCE NUMBER,
    STATION_TYPE VARCHAR(30)
);

INSERT INTO DIM_STATION (
    STATION_ID,
    STATION_NAME,
    LINE_ID,
    LINE_NAME,
    STATION_SEQUENCE,
    STATION_TYPE
)
SELECT
    STATION_ID,
    STATION_NAME,
    LINE_ID,
    LINE_NAME,
    STATION_SEQUENCE,
    STATION_TYPE
FROM METRO_DB.RAW.STATIONS;


-- Trip Fact Table

CREATE OR REPLACE TABLE FACT_TRIPS (
    TRIP_ID VARCHAR(30),
    PASSENGER_ID VARCHAR(20),
    ENTRY_STATION_ID VARCHAR(10),
    EXIT_STATION_ID VARCHAR(10),
    TRAVEL_DATE DATE,
    ENTRY_TIME TIMESTAMP,
    EXIT_TIME TIMESTAMP,
    FARE NUMBER(10,2)
);


-- Verify tables

SHOW TABLES IN SCHEMA METRO_DB.DW;
