-- MetroPulse360
-- 05 - Incremental Processing with Streams & Tasks

USE DATABASE METRO_DB;
USE WAREHOUSE METRO_WH;


-- Staging table

USE SCHEMA STAGING;

CREATE OR REPLACE TABLE METRO_TRIPS_STAGING (
    TRIP_ID VARCHAR(30),
    PASSENGER_ID VARCHAR(20),
    ENTRY_STATION_ID VARCHAR(10),
    EXIT_STATION_ID VARCHAR(10),
    TRAVEL_DATE DATE,
    FARE NUMBER(10,2),
    LOADED_AT TIMESTAMP,
    PROCESSED_AT TIMESTAMP
);


-- Stream on RAW table

USE SCHEMA RAW;

CREATE OR REPLACE STREAM METRO_TRIPS_RAW_STREAM
ON TABLE METRO_TRIPS_RAW;


-- Task for incremental processing

USE SCHEMA STAGING;

CREATE OR REPLACE TASK LOAD_METRO_TRIPS_STAGING
WAREHOUSE = METRO_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA(
    'METRO_DB.RAW.METRO_TRIPS_RAW_STREAM'
)
AS
INSERT INTO METRO_DB.STAGING.METRO_TRIPS_STAGING (
    TRIP_ID,
    PASSENGER_ID,
    ENTRY_STATION_ID,
    EXIT_STATION_ID,
    TRAVEL_DATE,
    FARE,
    LOADED_AT,
    PROCESSED_AT
)
SELECT
    TRIP_ID,
    PASSENGER_ID,
    ENTRY_STATION_ID,
    EXIT_STATION_ID,
    TRAVEL_DATE,
    FARE,
    LOADED_AT,
    CURRENT_TIMESTAMP()
FROM METRO_DB.RAW.METRO_TRIPS_RAW_STREAM
WHERE METADATA$ACTION = 'INSERT';


-- Enable the task

ALTER TASK LOAD_METRO_TRIPS_STAGING RESUME;


-- Verify

SHOW STREAMS;

SHOW TASKS;
