-- MetroPulse360
-- 03 - Azure ADLS Gen2 Integration

USE DATABASE METRO_DB;
USE WAREHOUSE METRO_WH;

-- Azure Storage Integration
-- Replace <AZURE_TENANT_ID> with your own value.
-- Do not commit real account-specific credentials to GitHub.

CREATE OR REPLACE STORAGE INTEGRATION METRO_AZURE_INTEGRATION
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'AZURE'
ENABLED = TRUE
AZURE_TENANT_ID = '<AZURE_TENANT_ID>'
STORAGE_ALLOWED_LOCATIONS = (
    'azure://<STORAGE_ACCOUNT>.blob.core.windows.net/<CONTAINER>/<FOLDER>/'
);

-- Check integration configuration
DESC INTEGRATION METRO_AZURE_INTEGRATION;


-- CSV File Format

USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT METRO_CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE;


-- External Azure Stage

CREATE OR REPLACE STAGE METRO_AZURE_STAGE
URL = 'azure://<STORAGE_ACCOUNT>.blob.core.windows.net/<CONTAINER>/<FOLDER>/'
STORAGE_INTEGRATION = METRO_AZURE_INTEGRATION
FILE_FORMAT = METRO_CSV_FORMAT;


-- Raw Trip Table

CREATE OR REPLACE TABLE METRO_TRIPS_RAW (
    TRIP_ID VARCHAR(30),
    PASSENGER_ID VARCHAR(20),
    ENTRY_STATION_ID VARCHAR(10),
    EXIT_STATION_ID VARCHAR(10),
    TRAVEL_DATE DATE,
    FARE NUMBER(10,2),
    LOADED_AT TIMESTAMP
);


-- Verify files available in Azure

LIST @METRO_AZURE_STAGE;
