-- MetroPulse360
-- 04 - Snowpipe Automated Ingestion

USE DATABASE METRO_DB;
USE SCHEMA RAW;
USE WAREHOUSE METRO_WH;

-- Azure notification integration
-- Replace placeholders with your own Azure values.

CREATE OR REPLACE NOTIFICATION INTEGRATION METRO_AZURE_NOTIFICATION
ENABLED = TRUE
TYPE = QUEUE
NOTIFICATION_PROVIDER = AZURE_STORAGE_QUEUE
AZURE_STORAGE_QUEUE_PRIMARY_URI =
    'https://<STORAGE_ACCOUNT>.queue.core.windows.net/<QUEUE_NAME>'
AZURE_TENANT_ID = '<AZURE_TENANT_ID>';


-- Snowpipe

CREATE OR REPLACE PIPE METRO_TRIPS_PIPE
AUTO_INGEST = TRUE
INTEGRATION = 'METRO_AZURE_NOTIFICATION'
AS
COPY INTO METRO_TRIPS_RAW
FROM @METRO_AZURE_STAGE
FILE_FORMAT = METRO_CSV_FORMAT
ON_ERROR = 'CONTINUE';


-- Verify Snowpipe

SHOW PIPES;

SELECT SYSTEM$PIPE_STATUS('METRO_TRIPS_PIPE');
