-- MetroPulse360
-- 08 - Snowflake Dynamic Table

USE DATABASE METRO_DB;
USE SCHEMA ANALYTICS;
USE WAREHOUSE METRO_WH;

CREATE OR REPLACE DYNAMIC TABLE DT_DAILY_RIDERSHIP
TARGET_LAG = '1 hour'
WAREHOUSE = METRO_WH
AS
SELECT
    TRAVEL_DATE,
    COUNT(*) AS TOTAL_TRIPS,
    COUNT(DISTINCT PASSENGER_ID) AS UNIQUE_PASSENGERS,
    SUM(FARE) AS TOTAL_REVENUE,
    ROUND(AVG(FARE), 2) AS AVERAGE_FARE
FROM METRO_DB.DW.FACT_TRIPS
GROUP BY TRAVEL_DATE;


-- Verify Dynamic Table

SELECT *
FROM DT_DAILY_RIDERSHIP
ORDER BY TRAVEL_DATE;
